CREATE TABLE IF NOT EXISTS authors (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    surname varchar(50) NOT NULL,
    forename varchar(50) NOT NULL DEFAULT '' -- for mononyms e.g. Plato
);

CREATE TABLE IF NOT EXISTS books (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar(50) NOT NULL,
    author integer NOT NULL REFERENCES authors
);
