CREATE TABLE IF NOT EXISTS authors (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- consider using serial for smaller size
    surname varchar(50) NOT NULL,
    forename varchar(50) NOT NULL DEFAULT '', -- for mononyms e.g. Plato
    born smallint,
    died smallint
);

CREATE TABLE IF NOT EXISTS books (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar(50) NOT NULL,
    author_id integer NOT NULL REFERENCES authors ON DELETE CASCADE
);
