create table if not exists exercise_sets (
    id integer primary key generated by default as identity,
    name varchar(50) not null,
    performed_at timestamp default (now()),
    weight smallint not null default 0,
    unit varchar(4) not null default 'lbs',
    reps smallint not null default 0,
    set_count smallint not null default 1,
    notes text default '',
    split_day varchar(20) default '',
    program varchar(50) default '',
    tags text default ''
);

create table if not exists library_branches (
    id integer primary key generated by default as identity,
    name varchar(50) not null,
    city varchar(50) not null,
    state varchar(50) not null
);
